# entry-point into grammar (will probably have to refactor if complicated structures to be introduced e.g. loops, functions etc.)
program ::= statementList
statementList ::= statement ";" statementList | epsilon

statement ::= var_declaration | statement_assignment | hardcoded_output # unlikely that primitive functions like hardcoded_output will be implemented this way in final product
statement_assignment ::= var assignment
hardcoded_output = "output(" expr ")"

var_declaration ::= "let" var var_declaration_prime
var_declaration_prime ::= assignment | epsilon

var ::= ("dist" dist_type | "res" res_type) VAR_NAME

dist_type ::= "uniform" # only uniform distribution for now

res_type ::= "int" # only ints as a value type for now

assignment ::= "=" expr 

expr ::= additive_term | dist_inst 
dist_inst = dist_type "(" arg_list ")"

additive_term ::= multiplicative_term (("+"|"-") multiplicative_term)*
multiplicative_term ::= unary_term (("*"|"/") unary_term)*

unary_term ::= "-" unary_term | primary_term

primary_term ::= "(" expr ")" 
    | var_usage
    | INT_LIT

var_usage = VAR_NAME opt_fun_call
opt_fun_call = ":" VAR_NAME "(" arg_list ")" | epsilon

dist_inst = DIST_NAME "(" arg_list ")"

arg_list = arg ("," arg)* | epsilon
arg = expr 

param_list = param ("," param)* | epsilon 
param = VAR_NAME
