# entry-point into grammar (will probably have to refactor when introducing functions, loops etc.)
# may also have to refactor grammar to put ";" at different levels to provide better error messages
program ::= statementList
statementList ::= statement ";" statementList | epsilon

statement ::= var_declaration | statement_assignment | hardcoded_output # hardcoded_output temp
statement_assignment ::= var assignment
hardcoded_output = "output(" expr ")"

var_declaration ::= "let" var var_declaration_prime
var_declaration_prime ::= assignment | epsilon

var ::= ("dist" dist_type | "res" res_type) VAR_NAME

dist_type ::= "uniform" # only implementing uniform for now

res_type ::= "int" # only int for now

assignment ::= "=" expr 

expr ::= additive_term | dist_inst # need to extend this to bool operators later

additive_term ::= multiplicative_term (("+"|"-") multiplicative_term)*
multiplicative_term ::= unary_term (("*"|"/") unary_term)*

unary_term ::= "-" unary_term | primary_term

primary_term ::= "(" expr ")" 
    | var_usage
    | INT_LIT

var_usage = VAR_NAME opt_fun_call
opt_fun_call = ":" VAR_NAME "(" arg_list ")" | epsilon

dist_inst = DIST_NAME "(" arg_list ")"

arg_list = arg ("," arg)* | epsilon
arg = expr 

param_list = param ("," param)* | epsilon 
param = VAR_NAME
